name: oamanagev1
description: "oamanagev1"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.2.0
  mobile_scanner: ^6.0.2
  collection: ^1.18.0
  intl: ^0.19.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock/users.json
    - assets/mock/assets.json
    - assets/mock/asset_inspections.json
